import * as vscode from 'vscode';
import type { ChatMessage, ChatMode, DisplayItem, SessionMeta } from '../types';
import type { SerializedCheckpoint } from '../agent/checkpoints';

export interface StoredSession {
  id: string;
  title: string;
  /** True once the title was auto-generated by the model (not a fallback). */
  titleAuto?: boolean;
  updatedAt: number;
  addedLines: number;
  removedLines: number;
  changedFilePaths: string[];
  modelMessages: ChatMessage[];
  display: DisplayItem[];
  checkpoints?: SerializedCheckpoint[];
  /** The model/agent and machine this chat last ran with. */
  modelId?: string;
  modelKey?: string;
  modelLabel?: string;
  machineName?: string;
  mode?: ChatMode;
}

const LEGACY_SESSIONS_KEY = 'nyx.sessions.v1';
const MAX_SESSIONS = 50;

/**
 * Persists chat sessions as individual JSON files under the extension's
 * workspace storage. Unlike the previous Memento-based store, saving one
 * session no longer re-serializes every other session, and sessions are
 * inspectable/exportable on disk. A lightweight meta index lives in memory.
 */
export class SessionStore {
  private metas: SessionMeta[] = [];
  private loaded = false;

  constructor(
    private readonly storageUri: vscode.Uri,
    private readonly legacyState: vscode.Memento,
  ) {}

  private get dir(): vscode.Uri {
    return vscode.Uri.joinPath(this.storageUri, 'sessions');
  }

  private fileFor(id: string): vscode.Uri {
    return vscode.Uri.joinPath(this.dir, `${id.replace(/[^a-zA-Z0-9_-]/g, '_')}.json`);
  }

  /** Loads the index (and migrates legacy Memento sessions on first run). */
  async init(): Promise<void> {
    if (this.loaded) {
      return;
    }
    this.loaded = true;
    await vscode.workspace.fs.createDirectory(this.dir).then(undefined, () => undefined);

    // One-time migration from the old Memento store.
    const legacy = this.legacyState.get<StoredSession[]>(LEGACY_SESSIONS_KEY);
    if (legacy && legacy.length > 0) {
      for (const session of legacy) {
        await this.writeFile(session).catch(() => undefined);
      }
      await this.legacyState.update(LEGACY_SESSIONS_KEY, undefined);
    }

    const metas: SessionMeta[] = [];
    let entries: [string, vscode.FileType][] = [];
    try {
      entries = await vscode.workspace.fs.readDirectory(this.dir);
    } catch {
      entries = [];
    }
    for (const [name, type] of entries) {
      if (type !== vscode.FileType.File || !name.endsWith('.json')) {
        continue;
      }
      try {
        const session = await this.readFile(vscode.Uri.joinPath(this.dir, name));
        if (session) {
          metas.push(toMeta(session));
        }
      } catch {
        // Skip corrupt files.
      }
    }
    metas.sort((a, b) => b.updatedAt - a.updatedAt);
    this.metas = metas;
  }

  list(): SessionMeta[] {
    return this.metas;
  }

  async get(id: string): Promise<StoredSession | undefined> {
    try {
      return await this.readFile(this.fileFor(id));
    } catch {
      return undefined;
    }
  }

  async save(session: StoredSession): Promise<void> {
    await this.writeFile(session);
    this.metas = [toMeta(session), ...this.metas.filter((m) => m.id !== session.id)];
    // Enforce the cap by dropping the oldest sessions.
    while (this.metas.length > MAX_SESSIONS) {
      const oldest = this.metas.pop();
      if (oldest) {
        await vscode.workspace.fs.delete(this.fileFor(oldest.id)).then(undefined, () => undefined);
      }
    }
  }

  async remove(id: string): Promise<void> {
    this.metas = this.metas.filter((m) => m.id !== id);
    await vscode.workspace.fs.delete(this.fileFor(id)).then(undefined, () => undefined);
  }

  private async readFile(uri: vscode.Uri): Promise<StoredSession | undefined> {
    const bytes = await vscode.workspace.fs.readFile(uri);
    const data = JSON.parse(new TextDecoder().decode(bytes)) as StoredSession;
    return data && typeof data.id === 'string' ? data : undefined;
  }

  private async writeFile(session: StoredSession): Promise<void> {
    await vscode.workspace.fs.createDirectory(this.dir).then(undefined, () => undefined);
    const bytes = new TextEncoder().encode(JSON.stringify(session));
    await vscode.workspace.fs.writeFile(this.fileFor(session.id), bytes);
  }
}

function toMeta(s: StoredSession): SessionMeta {
  return {
    id: s.id,
    title: s.title,
    updatedAt: s.updatedAt,
    addedLines: s.addedLines,
    removedLines: s.removedLines ?? 0,
    changedFiles: s.changedFilePaths.length,
    modelLabel: s.modelLabel,
    machineName: s.machineName,
    mode: s.mode,
  };
}
